apiVersion: v1
kind: ConfigMap
data:
  API_VERSION: "1"
  APP_PORT: "8000"
  CORS_WHITELIST: '["https://localhost:3000","https://localhost:8000"]'
  POSTGRES_DB: gateway_db
  POSTGRES_USER: gateway_user
  POSTGRES_PASSWORD: gateway_password
  DB_HOST: api-gateway-db-service
  DB_NAME: gateway_db
  DB_PORT: "5432"
  DEBUG: "1"
  BROKER_URL: amqp://guest:guest@api-gateway-rabbitmq-service:5672/
  DOMAIN: localhost
  EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
  EMAIL_HOST: smtp.gmail.com
  EMAIL_PORT: "587"
  EMAIL_USE_SSL: "True"
  EMAIL_USE_TLS: "True"
  ENGINE: django_tenants.postgresql_backend
  GOOGLE_ACCOUNTS_BASE_URL: https://oauth2.googleapis.com/token
  MDS_CRM_REDIRECT_URI: http://localhost:8000/v1/microsoft_crm/redirect/
  MICROSOFT_ME_URL: https://graph.microsoft.com/v1.0/me?
  OUTLOOK_ACCOUNTS_BASE_URL: https://login.microsoftonline.com/common/oauth2/v2.0/token/
  REDIRECT_URI: http://localhost:8000/v1/mail_sync/redirect/
  SALESFORCE_CRM_COMPANY: heckerbellatest-dev-ed
  SALESFORCE_CRM_REDIRECT_URI: http://localhost:8000/v1/salesforce_crm/redirect/
  USE_S3: "FALSE"
  YAHOO_ACCOUNTS_BASE_URL: https://api.login.yahoo.com/oauth2/get_token/

metadata:
  labels:
    app: api-gateway-env
  name: env
